const englishTitle = [
  { id: 23, title: "Grilled Pork Belly" },
  { id: 9, title: "Brown Rice" },
  { id: 25, title: "Tteokbokki" },
  { id: 1, title: "Steamed Rice" },
  { id: 8, title: "Mixed Grain Rice" },
  { id: 30, title: "Crunchy Taco" },
  { id: 22, title: "Steamed Sweet Potato" },
  { id: 18, title: "Steamed Potato" },
  { id: 26, title: "Vegetable Salad (with Dressing)" },
  { id: 6, title: "Banana" },
  { id: 4, title: "Fried Egg" },
  { id: 24, title: "Tofu" },
  { id: 2, title: "Boiled Egg" },
  { id: 20, title: "Milk" },
  { id: 16, title: "Korean Melon" },
  { id: 10, title: "Apple" },
  { id: 5, title: "Watermelon" },
  { id: 29, title: "Onion" },
  { id: 7, title: "Kimchi" },
  { id: 15, title: "Plum" },
  { id: 27, title: "Cabbage" },
  { id: 14, title: "Cucumber" },
  { id: 17, title: "Lettuce" },
  { id: 21, title: "Blueberry" },
  { id: 12, title: "Tomato (Medium)" },
  { id: 28, title: "Leaf Lettuce" },
  { id: 11, title: "Almond" },
  { id: 13, title: "Americano" },
  { id: 3, title: "Cherry Tomato" },
  { id: 19, title: "Grape Tomato" },
];

export default englishTitle;
